name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew app:assembleRelease --no-daemon

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: RedirectCameraHook-Release
        path: |
          # Secara eksplisit
          app/build/outputs/apk/release/CameraRedirect-release.apk
          # Atau pakai wildcard supaya fleksibel
          app/build/outputs/apk/release/*.apk
